version: '3.9'

services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: micro_db
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5673:5672"
      - "15673:15672"

  user-service:
    build:
      context: .
      dockerfile: ./user-service/Dockerfile
    ports:
      - "3002:3002"
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_started

  post-service:
    build:
      context: .
      dockerfile: ./post-service/Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_started
